### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

### ISSUE THREAD

**Issue by ghost** [jichengyuan/Vision_GNN#1]
running eval.sh, meet this problem?

**Comment by jichengyuan** [comment]
Hi,

could you tell me which version of Pytorch you are using?

**Comment by ghost** [comment]
Thanks for your answer, but not the problem of the Pytorch. Past I running the project on the Windows, meet so many problems(like this), later I running the project on the Linux, the problem disappears.

**Comment by ghost** [comment]
during find solution of this problem, I think it should be caused by inconsistent system encoding format, gbk conflict UTF-8?(Maybe

**Comment by jichengyuan** [comment]
aha. I think so.
